/**
 * The S3-compatible providers we support, and everything the app knows about
 * each one.
 *
 * This is the single source of truth. The routes under /connect/[provider], the
 * metadata on those pages, the sitemap entries, the picker cards and the setup
 * guide all read from here, so adding a provider is one edit rather than five.
 *
 * A word on why these pages are allowed to exist at all. Google penalises
 * "scaled content abuse": many pages identical but for one swapped variable.
 * These pages are defensible only because each provider genuinely differs -
 * different endpoint shape, different regions, different CORS steps, different
 * permission names. Keep it that way. A provider added here with copied copy
 * and an empty setup section is a doorway page, and those are penalised site
 * wide rather than page by page.
 */

export interface RegionOption {
  value: string;
  label: string;
}

export interface S3Provider {
  /** URL segment. Written the way people search, not the way we store it. */
  slug: string;
  /** Key into the CORS snippets in config/cors.ts. */
  id: string;
  name: string;
  /** One line on the picker card. */
  tagline: string;
  /** Brand-adjacent colour for the provider mark. */
  accent: string;
  /** Endpoint template. `{{region}}` and `{{accountId}}` are substituted. */
  endpoint: string;
  defaultRegion: string;
  regions: RegionOption[];
  /** True when the endpoint cannot be derived and the user must supply it. */
  requiresCustomEndpoint: boolean;
  seo: {
    title: string;
    description: string;
    h1: string;
    /** Opening paragraph. Provider-specific, never generated by templating. */
    intro: string;
  };
  setup: {
    corsInstructions: string;
    permissions: string[];
    docsUrl: string;
    docsLabel: string;
    /** Anything about this provider that trips people up. */
    gotcha?: string;
  };
}

const AWS_REGIONS: RegionOption[] = [
  { value: 'us-east-1', label: 'US East (N. Virginia) - us-east-1' },
  { value: 'us-east-2', label: 'US East (Ohio) - us-east-2' },
  { value: 'us-west-1', label: 'US West (N. California) - us-west-1' },
  { value: 'us-west-2', label: 'US West (Oregon) - us-west-2' },
  { value: 'ap-south-1', label: 'Asia Pacific (Mumbai) - ap-south-1' },
  { value: 'ap-northeast-1', label: 'Asia Pacific (Tokyo) - ap-northeast-1' },
  { value: 'ap-northeast-2', label: 'Asia Pacific (Seoul) - ap-northeast-2' },
  { value: 'ap-northeast-3', label: 'Asia Pacific (Osaka) - ap-northeast-3' },
  { value: 'ap-southeast-1', label: 'Asia Pacific (Singapore) - ap-southeast-1' },
  { value: 'ap-southeast-2', label: 'Asia Pacific (Sydney) - ap-southeast-2' },
  { value: 'ap-southeast-3', label: 'Asia Pacific (Jakarta) - ap-southeast-3' },
  { value: 'ca-central-1', label: 'Canada (Central) - ca-central-1' },
  { value: 'eu-central-1', label: 'Europe (Frankfurt) - eu-central-1' },
  { value: 'eu-west-1', label: 'Europe (Ireland) - eu-west-1' },
  { value: 'eu-west-2', label: 'Europe (London) - eu-west-2' },
  { value: 'eu-west-3', label: 'Europe (Paris) - eu-west-3' },
  { value: 'eu-north-1', label: 'Europe (Stockholm) - eu-north-1' },
  { value: 'eu-south-1', label: 'Europe (Milan) - eu-south-1' },
  { value: 'me-south-1', label: 'Middle East (Bahrain) - me-south-1' },
  { value: 'sa-east-1', label: 'South America (Sao Paulo) - sa-east-1' },
  { value: 'af-south-1', label: 'Africa (Cape Town) - af-south-1' },
];

export const S3_PROVIDERS: readonly S3Provider[] = [
  {
    slug: 'aws-s3',
    id: 'aws',
    name: 'Amazon S3',
    tagline: 'The original object store',
    accent: '#E8912D',
    endpoint: '',
    defaultRegion: 'us-east-1',
    regions: AWS_REGIONS,
    requiresCustomEndpoint: false,
    seo: {
      title: 'Amazon S3 Bucket Browser in Your Web Browser',
      description:
        'Browse, upload and share files in an Amazon S3 bucket from your browser. Bring your own IAM keys. Nothing is uploaded to our servers.',
      h1: 'Connect Opndrive to Amazon S3',
      intro:
        'Opndrive talks to the S3 API directly from your browser using IAM credentials you supply. There is no account to create and no server of ours in the path, so your objects go straight between your machine and AWS.',
    },
    setup: {
      corsInstructions:
        'Open the S3 console, choose your bucket, then Permissions, then Cross-origin resource sharing (CORS).',
      permissions: ['s3:GetObject', 's3:PutObject', 's3:DeleteObject', 's3:ListBucket'],
      docsUrl: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html',
      docsLabel: 'AWS S3 CORS documentation',
      gotcha:
        'Scope the IAM policy to this one bucket. A key with account-wide S3 access is stored in your browser and does far more than this app needs.',
    },
  },
  {
    slug: 'cloudflare-r2',
    id: 'cloudflare',
    name: 'Cloudflare R2',
    tagline: 'S3 API with no egress fees',
    accent: '#F26B21',
    endpoint: 'https://{{accountId}}.r2.cloudflarestorage.com',
    defaultRegion: 'auto',
    regions: [
      { value: 'auto', label: 'Automatic - auto' },
      { value: 'wnam', label: 'Western North America - wnam' },
      { value: 'enam', label: 'Eastern North America - enam' },
      { value: 'weur', label: 'Western Europe - weur' },
      { value: 'eeur', label: 'Eastern Europe - eeur' },
      { value: 'apac', label: 'Asia Pacific - apac' },
    ],
    requiresCustomEndpoint: true,
    seo: {
      title: 'Cloudflare R2 Web Client and Bucket Browser',
      description:
        'A browser UI for Cloudflare R2. Paste an R2 API token, browse your bucket, upload and share. Credentials stay in your browser.',
      h1: 'Connect Opndrive to Cloudflare R2',
      intro:
        'R2 speaks the S3 API, so Opndrive works with it directly. You will need your account ID for the endpoint, since R2 addresses buckets per account rather than per region.',
    },
    setup: {
      corsInstructions:
        'Open the Cloudflare dashboard, go to R2 Object Storage, choose your bucket, then Settings, then CORS Policy.',
      permissions: ['Read', 'Write', 'Delete', 'List'],
      docsUrl: 'https://developers.cloudflare.com/r2/api/s3/api/',
      docsLabel: 'Cloudflare R2 S3 API documentation',
      gotcha:
        'The region is almost always "auto". The endpoint contains your account ID, not a region, so copy it from the R2 bucket settings page.',
    },
  },
  {
    slug: 'wasabi',
    id: 'wasabi',
    name: 'Wasabi',
    tagline: 'Flat-rate hot storage',
    accent: '#00A651',
    endpoint: 'https://s3.{{region}}.wasabisys.com',
    defaultRegion: 'us-east-1',
    regions: [
      { value: 'us-east-1', label: 'US East 1 (N. Virginia) - us-east-1' },
      { value: 'us-east-2', label: 'US East 2 (N. Virginia) - us-east-2' },
      { value: 'us-central-1', label: 'US Central 1 (Texas) - us-central-1' },
      { value: 'us-west-1', label: 'US West 1 (Oregon) - us-west-1' },
      { value: 'eu-central-1', label: 'EU Central 1 (Amsterdam) - eu-central-1' },
      { value: 'eu-central-2', label: 'EU Central 2 (Frankfurt) - eu-central-2' },
      { value: 'eu-west-1', label: 'EU West 1 (London) - eu-west-1' },
      { value: 'eu-west-2', label: 'EU West 2 (Paris) - eu-west-2' },
      { value: 'ap-northeast-1', label: 'AP Northeast 1 (Tokyo) - ap-northeast-1' },
      { value: 'ap-northeast-2', label: 'AP Northeast 2 (Osaka) - ap-northeast-2' },
      { value: 'ap-southeast-1', label: 'AP Southeast 1 (Singapore) - ap-southeast-1' },
      { value: 'ap-southeast-2', label: 'AP Southeast 2 (Sydney) - ap-southeast-2' },
    ],
    requiresCustomEndpoint: false,
    seo: {
      title: 'Wasabi S3 UI and Bucket Browser',
      description:
        'A web interface for Wasabi hot cloud storage. Connect with your Wasabi access keys and manage files from the browser.',
      h1: 'Connect Opndrive to Wasabi',
      intro:
        'Wasabi is S3-compatible, so Opndrive connects with a normal access key pair. The endpoint is derived from the region you pick, and the region must match the one your bucket was created in.',
    },
    setup: {
      corsInstructions:
        'Log into the Wasabi console, choose your bucket, then Policies, then CORS Configuration.',
      permissions: ['GetObject', 'PutObject', 'DeleteObject', 'ListBucket'],
      docsUrl:
        'https://wasabi-support.zendesk.com/hc/en-us/articles/360015106031-How-do-I-enable-CORS-on-my-bucket-',
      docsLabel: 'Wasabi CORS documentation',
      gotcha:
        'Wasabi regions are not interchangeable with AWS ones. Using the wrong region gives an authorization error rather than a helpful redirect.',
    },
  },
  {
    slug: 'backblaze-b2',
    id: 'backblaze',
    name: 'Backblaze B2',
    tagline: 'Low-cost cloud storage',
    accent: '#D8232F',
    endpoint: 'https://s3.{{region}}.backblazeb2.com',
    defaultRegion: 'us-west-002',
    regions: [
      { value: 'us-west-002', label: 'US West (California) - us-west-002' },
      { value: 'us-west-001', label: 'US West (Arizona) - us-west-001' },
      { value: 'eu-central-003', label: 'EU Central (Amsterdam) - eu-central-003' },
    ],
    requiresCustomEndpoint: false,
    seo: {
      title: 'Backblaze B2 File Browser with S3 Support',
      description:
        'Browse and manage a Backblaze B2 bucket from your browser using the S3-compatible API and your own application key.',
      h1: 'Connect Opndrive to Backblaze B2',
      intro:
        'B2 offers an S3-compatible endpoint alongside its native API, and Opndrive uses the former. Create an application key scoped to the bucket you want to browse.',
    },
    setup: {
      corsInstructions:
        'CORS on B2 is set from the command line. Install the b2 CLI, authenticate, then apply a CORS rules file to the bucket.',
      permissions: ['listFiles', 'readFiles', 'writeFiles', 'deleteFiles'],
      docsUrl:
        'https://www.backblaze.com/docs/cloud-storage-enable-cors-with-the-cli#add-cors-rules-with-a-json-file-(macos-and-linux)',
      docsLabel: 'Backblaze B2 CORS documentation',
      gotcha:
        'The B2 console has no CORS editor, so this is the one provider here where you cannot finish setup in a web dashboard.',
    },
  },
  {
    slug: 'minio',
    id: 'minio',
    name: 'MinIO',
    tagline: 'Self-hosted object storage',
    accent: '#C72E49',
    endpoint: '',
    defaultRegion: 'us-east-1',
    regions: [{ value: 'us-east-1', label: 'US East 1 - us-east-1' }],
    requiresCustomEndpoint: true,
    seo: {
      title: 'MinIO Browser and Web UI for Your Own Server',
      description:
        'A web UI for a self-hosted MinIO server. Point Opndrive at your endpoint, use your access keys, and browse buckets from the browser.',
      h1: 'Connect Opndrive to MinIO',
      intro:
        'MinIO runs on your own infrastructure, so there is no region list to choose from and you supply the endpoint yourself. Anything the S3 API supports, Opndrive can use.',
    },
    setup: {
      corsInstructions:
        'Configure CORS with the MinIO client (mc) or through the MinIO Console under Buckets, then your bucket, then Summary and Access Policy.',
      permissions: ['s3:GetObject', 's3:PutObject', 's3:DeleteObject', 's3:ListBucket'],
      docsUrl: 'https://min.io/docs/minio/linux/developers/javascript/API.html',
      docsLabel: 'MinIO JavaScript API documentation',
      gotcha:
        'Your browser has to be able to reach the endpoint. A MinIO server on a private network will not work from the hosted app, so self-host Opndrive alongside it.',
    },
  },
];

/** Every provider slug, for generateStaticParams and the sitemap. */
export const PROVIDER_SLUGS: readonly string[] = S3_PROVIDERS.map((provider) => provider.slug);

export function getProviderBySlug(slug: string): S3Provider | undefined {
  return S3_PROVIDERS.find((provider) => provider.slug === slug);
}

/** Resolves an endpoint template against the values a user has entered. */
export function resolveEndpoint(provider: S3Provider, region: string): string {
  return provider.endpoint.replace('{{region}}', region);
}
